### ISSUE TITLE
DM7020HD

### ISSUE THREAD

**Issue by EnoSat** [satdreamgr/Satdreamgr-HD-TranspBA#18]
After last update missing Select audio track and Select subtitle (in default skin show ok)
<a href="https://postimg.cc/PCqV55fd" target="_blank"><img src="https://i.postimg.cc/PCqV55fd/1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021213740.jpg" alt="1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021213740"/></a>
<a href="https://postimg.cc/fSZBnwgn" target="_blank"><img src="https://i.postimg.cc/fSZBnwgn/1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021213646.jpg" alt="1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021213646"/></a>
<a href="https://postimg.cc/yg0vbJjy" target="_blank"><img src="https://i.postimg.cc/yg0vbJjy/1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021213710.jpg" alt="1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021213710"/></a>
<a href="https://postimg.cc/bDzdnWZH" target="_blank"><img src="https://i.postimg.cc/bDzdnWZH/1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021222455.jpg" alt="1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021222455"/></a>
<a href="https://postimg.cc/Z9mqk2xt" target="_blank"><img src="https://i.postimg.cc/Z9mqk2xt/1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021222530.jpg" alt="1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021222530"/></a>
<a href="https://postimg.cc/rDxpPMWN" target="_blank"><img src="https://i.postimg.cc/rDxpPMWN/1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021222546.jpg" alt="1-0-19-BBB-103-22-BF-EEEE0000-0-0-0-20181021222546"/></a>

**Comment by nautilus7** [comment]
I cannot reproduce it here... But I have another box another and version of the image.

The skin hasn't got any updates recently regarding this screen, nor the screen itself has been updated in openpli or sdg in a way that would affect the skin.

Try updating again (if there are any updates available).
Maybe, by mistake, the skin package was updated to a version incompatible with sdg 4?
Perhaps @athoik or @devilcosta know what's wrong.

**Comment by athoik** [comment]
A new branch 4.0 was created with a fix applied. So you can try an update and report.

**Comment by EnoSat** [comment]
Hi, now after update fixed ;) good work :)
<a href="https://i.postimg.cc/dV9ZphtT/sdg01.png" target="_blank"><img src="https://i.postimg.cc/fVJb0Tdw/sdg01.png" alt="sdg01"/></a>
<a href="https://i.postimg.cc/nhxQ34ZJ/sdg02.png" target="_blank"><img src="https://i.postimg.cc/mtdDDFtX/sdg02.png" alt="sdg02"/></a>
<a href="https://i.postimg.cc/mr21sTtp/sdg03.png" target="_blank"><img src="https://i.postimg.cc/FY8Hb5b0/sdg03.png" alt="sdg03"/></a>
