### ISSUE TITLE
DM7020HD

### ISSUE THREAD

**Issue by EnoSat** [satdreamgr/Satdreamgr-HD-TranspBA#19]
[ePNG] couldn't open Satdreamgr-HD-TranspBA/weather_iconsna.png
[ePNG] couldn't open Satdreamgr-HD-TranspBA/weather_iconsna.png
[Skin] SKIN ERROR in screen 'Volume' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: component with name 'VolumeText' was not found in skin of screen 'Volume'!. Please contact the skin's author!

[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: component with name 'key_red' was not found in skin of screen 'Mess                                                                                                                                                             ageBox'!. Please contact the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: component with name 'key_green' was not found in skin of screen 'Me                                                                                                                                                             ssageBox'!. Please contact the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: component with name 'key_yellow' was not found in skin of screen 'M                                                                                                                                                             essageBox'!. Please contact the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: component with name 'key_blue' was not found in skin of screen 'Mes                                                                                                                                                             sageBox'!. Please contact the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: source 'key_red' was not found in screen 'MessageBox'!. Please cont                                                                                                                                                             act the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: source 'key_green' was not found in screen 'MessageBox'!. Please co                                                                                                                                                             ntact the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: source 'key_yellow' was not found in screen 'MessageBox'!. Please c                                                                                                                                                             ontact the skin's author!
[Skin] SKIN ERROR in screen 'MessageBox' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: source 'key_blue' was not found in screen 'MessageBox'!. Please con                                                                                                                                                             tact the skin's author!

[Skin] SKIN ERROR in screen 'EventView' widget 'widget': {Satdreamgr-HD-TranspBA/skin.xml}: component with name 'epg_eventname' was not found in skin of screen 'EventView'!. Please contact the skin's author!
[Skin] Attribute not implemented: objectTypes value: key_red,StaticText
[Skin] Attribute not implemented: objectTypes value: key_green,StaticText
[Skin] Attribute not implemented: objectTypes value: key_yellow,StaticText
[Skin] Attribute not implemented: objectTypes value: key_blue,StaticText
[Skin] Attribute not implemented: objectTypes value: key_yellow,Button,Label
[Skin] Attribute not implemented: objectTypes value: key_blue,Button,Label
[Skin] Attribute not implemented: objectTypes value: key_green,Button,Label
[Skin] Attribute not implemented: objectTypes value: key_red,Button,Label

**Comment by nautilus7** [comment]
Should be fixed by now.
