### ISSUE TITLE
Picture Camera

### ISSUE THREAD

**Issue by EnoSat** [satdreamgr/Satdreamgr-HD-TranspBA#42]
[Skin] Processing screen 'PictureCamera', position=(0, 0), size=(1280 x 720) for module 'PictureCamera'.
[Skin] Error in screen 'PictureCamera' widget 'widget': [Skin] {Satdreamgr-HD-TranspBA/skin.xml}: Component with name 'title' was not found in skin of screen 'PictureCamera'!!  Please contact the skin's author!

**Comment by devilcosta** [comment]
Thanks, we fixed the error!
